export const VALID_AGES = [
  { label: 'NR', value: 'NR' },
  { label: 'yearling', value: 'yearling' },
  { label: 'fing', value: 'fing' },
  { label: 'catchable', value: 'catchable' },
  { label: 'subcatch', value: 'subcatch' },
  { label: 'fry', value: 'fry' },
  { label: '0', value: '0' },
  { label: '2-3 yr', value: '2-3 yr' },
  { label: 'brood', value: 'brood' },
  { label: 'sac fry', value: 'sac fry' },
  { label: 'wild', value: 'wild' },
  { label: 'egg', value: 'egg' },
  { label: 'smolt', value: 'smolt' },
  { label: 'adult', value: 'adult' },
  { label: 'post smolt', value: 'post smolt' },
  { label: 'various', value: 'various' },
  { label: 'tadpole', value: 'tadpole' },
  { label: 'subyearling', value: 'subyearling' },
  { label: 'larvae', value: 'larvae' },
  { label: 'production', value: 'production' },
  { label: 'embryo', value: 'embryo' },
  { label: 'RTC-12', value: 'RTC-12' },
  { label: 'pre smolt', value: 'pre smolt' }
];
